//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingSoftware.App.LanguageSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_gb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_gb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motivation.Core.LanguageSupport.en-gb", typeof(en_gb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and login.
        /// </summary>
        internal static string AcceptAndLogin {
            get {
                return ResourceManager.GetString("AcceptAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement successfully added..
        /// </summary>
        internal static string AddAchievement {
            get {
                return ResourceManager.GetString("AddAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD GOAL .
        /// </summary>
        internal static string AddGoal {
            get {
                return ResourceManager.GetString("AddGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new goal.
        /// </summary>
        internal static string AddNewGoal {
            get {
                return ResourceManager.GetString("AddNewGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        internal static string AddNewMeasurement {
            get {
                return ResourceManager.GetString("AddNewMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new measure has been added..
        /// </summary>
        internal static string AddNewMeasurementDialog {
            get {
                return ResourceManager.GetString("AddNewMeasurementDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAP.
        /// </summary>
        internal static string Again {
            get {
                return ResourceManager.GetString("Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error....
        /// </summary>
        internal static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured! .
        /// </summary>
        internal static string AlertErrorMessage {
            get {
                return ResourceManager.GetString("AlertErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Center was unable to delete your device..
        /// </summary>
        internal static string AppcenterError {
            get {
                return ResourceManager.GetString("AppcenterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRIL.
        /// </summary>
        internal static string APRIL {
            get {
                return ResourceManager.GetString("APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUGUST.
        /// </summary>
        internal static string AUGUST {
            get {
                return ResourceManager.GetString("AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like server is not responding. Please, try again..
        /// </summary>
        internal static string BadGatewayMessage {
            get {
                return ResourceManager.GetString("BadGatewayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The biggest gaps.
        /// </summary>
        internal static string BiggestGaps {
            get {
                return ResourceManager.GetString("BiggestGaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader hasn&apos;t wrote any comment for this review yet.
        /// </summary>
        internal static string BlankComment {
            get {
                return ResourceManager.GetString("BlankComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera available.
        /// </summary>
        internal static string CameraAvailable {
            get {
                return ResourceManager.GetString("CameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose item .
        /// </summary>
        internal static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click next to continue or click OK to exit..
        /// </summary>
        internal static string ClickOkNext {
            get {
                return ResourceManager.GetString("ClickOkNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest manager.
        /// </summary>
        internal static string ClosestManager {
            get {
                return ResourceManager.GetString("ClosestManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment on current development.
        /// </summary>
        internal static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED SALES.
        /// </summary>
        internal static string CompletedSales {
            get {
                return ResourceManager.GetString("CompletedSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE-ON-ONE.
        /// </summary>
        internal static string Conversation {
            get {
                return ResourceManager.GetString("Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-on-ones.
        /// </summary>
        internal static string Conversations {
            get {
                return ResourceManager.GetString("Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucial.
        /// </summary>
        internal static string Crucial {
            get {
                return ResourceManager.GetString("Crucial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date not set.
        /// </summary>
        internal static string DateNotSet {
            get {
                return ResourceManager.GetString("DateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string DateUndefined {
            get {
                return ResourceManager.GetString("DateUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEADLINE.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string DeadlineDetails {
            get {
                return ResourceManager.GetString("DeadlineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECEMBER.
        /// </summary>
        internal static string DECEMBER {
            get {
                return ResourceManager.GetString("DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        internal static string DescriptionDetails {
            get {
                return ResourceManager.GetString("DescriptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string DescriptionTodo {
            get {
                return ResourceManager.GetString("DescriptionTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think your organization facilitates a satisfactory degree of professional development?.
        /// </summary>
        internal static string DevelopmentQuestion {
            get {
                return ResourceManager.GetString("DevelopmentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By this we mean the opportunities you have at your workplace to learn something new and develop professionally by taking on new tasks and solving new problems. Being able to learn and be challenged, expands your competences. Many are motivated by this form of personal and professional development..
        /// </summary>
        internal static string DevelopmentText {
            get {
                return ResourceManager.GetString("DevelopmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF File.
        /// </summary>
        internal static string DownloadPDFFile {
            get {
                return ResourceManager.GetString("DownloadPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag or use the buttons to increase or decrease quickly.
        /// </summary>
        internal static string DragUseButtons1 {
            get {
                return ResourceManager.GetString("DragUseButtons1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a scale from 1 to 10 to range what factors motivates you at work, where 10 refers to something that is very important to you.
        /// </summary>
        internal static string DragUseButtons2 {
            get {
                return ResourceManager.GetString("DragUseButtons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT TASK.
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email then  you can reset your password..
        /// </summary>
        internal static string EnableRecoverMessage {
            get {
                return ResourceManager.GetString("EnableRecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelent.
        /// </summary>
        internal static string Excelent {
            get {
                return ResourceManager.GetString("Excelent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is your current assessment of the situation?.
        /// </summary>
        internal static string Expectations {
            get {
                return ResourceManager.GetString("Expectations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        internal static string ExtraBenefits {
            get {
                return ResourceManager.GetString("ExtraBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are your organization’s available benefits motivating you in your day-to-day work?.
        /// </summary>
        internal static string ExtraBenefitsQuestion {
            get {
                return ResourceManager.GetString("ExtraBenefitsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think the organization’s available benefits are motivating in your everyday work life?.
        /// </summary>
        internal static string ExtraBenefitsText {
            get {
                return ResourceManager.GetString("ExtraBenefitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilitation and flexibility.
        /// </summary>
        internal static string FacilitationAndFlexibility {
            get {
                return ResourceManager.GetString("FacilitationAndFlexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think the organization facilitates and shows flexibility concerning your needs at work?.
        /// </summary>
        internal static string FacilitationAndFlexibilityQuestion {
            get {
                return ResourceManager.GetString("FacilitationAndFlexibilityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility in the workplace is often important – especially if you have children or other forms of commitments. A flexible employer might facilitate flexible hours and the opportunity to use your extra hours for some time off, the opportunity to work from home or other locations, and flexibility regarding when to go on vacation. Further, it would be an employer who, in general, facilitates in a way so that you can perform your job in the best possible way..
        /// </summary>
        internal static string FacilitationAndFlexibilityText {
            get {
                return ResourceManager.GetString("FacilitationAndFlexibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors.
        /// </summary>
        internal static string Factors {
            get {
                return ResourceManager.GetString("Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEBRUARY.
        /// </summary>
        internal static string FEBRUARY {
            get {
                return ResourceManager.GetString("FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your manager has signed the report from the one-on-one - now your turn!.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication and feedback.
        /// </summary>
        internal static string FeedbackAndCommunication {
            get {
                return ResourceManager.GetString("FeedbackAndCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think you are receiving satisfactory and relevant feedback and guidance concerning your work and performance?.
        /// </summary>
        internal static string FeedbackAndCommunicationQuestion {
            get {
                return ResourceManager.GetString("FeedbackAndCommunicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For an employee it is crucial to receive feedback on the work situation and performance. How am I actually doing at my job? For guidance and instruction to work well, there needs to be open communication and room to asks questions. Follow-ups from managers, happening at a regular basis, that are constructive and includes clear goals, are very important..
        /// </summary>
        internal static string FeedbackAndCommunicationText {
            get {
                return ResourceManager.GetString("FeedbackAndCommunicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully downloaded to directory.
        /// </summary>
        internal static string FileDownloaded {
            get {
                return ResourceManager.GetString("FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By cIicking on the review file, it will be opened in the pdf viewer.
        /// </summary>
        internal static string FileViewerInfo {
            get {
                return ResourceManager.GetString("FileViewerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string FirstProgressBarDescription {
            get {
                return ResourceManager.GetString("FirstProgressBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username or password?.
        /// </summary>
        internal static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send lost password.
        /// </summary>
        internal static string GetForgottenPassword {
            get {
                return ResourceManager.GetString("GetForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal: .
        /// </summary>
        internal static string GoalDetails {
            get {
                return ResourceManager.GetString("GoalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal is not set.
        /// </summary>
        internal static string GoalNotSet {
            get {
                return ResourceManager.GetString("GoalNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAL.
        /// </summary>
        internal static string GoalOverview {
            get {
                return ResourceManager.GetString("GoalOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your goals and achievement.
        /// </summary>
        internal static string GoalsAndAchievement {
            get {
                return ResourceManager.GetString("GoalsAndAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your goal has been updated..
        /// </summary>
        internal static string GoalUpdated {
            get {
                return ResourceManager.GetString("GoalUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning!.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD WORK.
        /// </summary>
        internal static string GoodWork {
            get {
                return ResourceManager.GetString("GoodWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a great extent.
        /// </summary>
        internal static string GreatExtent {
            get {
                return ResourceManager.GetString("GreatExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show your organization what motivates you at work!.
        /// </summary>
        internal static string HomeViewMessage {
            get {
                return ResourceManager.GetString("HomeViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common identity and vision.
        /// </summary>
        internal static string IdentityAndVision {
            get {
                return ResourceManager.GetString("IdentityAndVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think the organization have a clear identity, common goal and vision?.
        /// </summary>
        internal static string IdentityAndVisionQuestion {
            get {
                return ResourceManager.GetString("IdentityAndVisionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some organizations succeed well in establishing a clear, common identity, making the employees proud to be representing and working for the company and feeling like they contribute to a community and something more than their own individual goals. There might be developed a set of values over time and a connection between the organization and the employees that they value and identify with. Common core values and a clear vision in an organization can make the work seem more meaningful..
        /// </summary>
        internal static string IdentityAndVisionText {
            get {
                return ResourceManager.GetString("IdentityAndVisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat important.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how you ranked all the motivation factors.
        /// </summary>
        internal static string ImprovementTitle {
            get {
                return ResourceManager.GetString("ImprovementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the buttons to increase or decrease a value.
        /// </summary>
        internal static string IncreaseDecreaseButton {
            get {
                return ResourceManager.GetString("IncreaseDecreaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report cannot be downloaded until the leader has signed it..
        /// </summary>
        internal static string InvalidDownload {
            get {
                return ResourceManager.GetString("InvalidDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be loaded or it loaded incorrectly. Please try again or contact support..
        /// </summary>
        internal static string InvalidFileLoad {
            get {
                return ResourceManager.GetString("InvalidFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codetermination.
        /// </summary>
        internal static string Involvement {
            get {
                return ResourceManager.GetString("Involvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you feel that you are able to influence your own work situation?.
        /// </summary>
        internal static string InvolvementQuestion {
            get {
                return ResourceManager.GetString("InvolvementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thrive on having a clear impact on their own work situation and by working in a place where there is room to voice your own opinions. This can include what tasks your day should consist of and how you are supposed to perform them. To have a clear influence on your own day-to-day work and feel heard can be considered very important to many..
        /// </summary>
        internal static string InvolvementText {
            get {
                return ResourceManager.GetString("InvolvementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JANUARY.
        /// </summary>
        internal static string JANUARY {
            get {
                return ResourceManager.GetString("JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNE.
        /// </summary>
        internal static string JUNE {
            get {
                return ResourceManager.GetString("JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language error.
        /// </summary>
        internal static string LanguageError {
            get {
                return ResourceManager.GetString("LanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language not set in company settings.
        /// </summary>
        internal static string LanguageErrorMessage {
            get {
                return ResourceManager.GetString("LanguageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select one of the languages for the application.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your leader.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report cannot be signed until leader has signed it first..
        /// </summary>
        internal static string LeaderNotSigned {
            get {
                return ResourceManager.GetString("LeaderNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LESS.
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been successfully logged in. Thanks for using Emotivation service..
        /// </summary>
        internal static string LoggedInMessage {
            get {
                return ResourceManager.GetString("LoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        internal static string LoggedInTitle {
            get {
                return ResourceManager.GetString("LoggedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        internal static string loggin_recover_sent {
            get {
                return ResourceManager.GetString("loggin_recover_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authentication is expired, please login again..
        /// </summary>
        internal static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to log out. Do you want to continue with this action?.
        /// </summary>
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        internal static string LostPasswordTitle {
            get {
                return ResourceManager.GetString("LostPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager: .
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed by manager.
        /// </summary>
        internal static string ManagerSignatureHeader {
            get {
                return ResourceManager.GetString("ManagerSignatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCH.
        /// </summary>
        internal static string MARCH {
            get {
                return ResourceManager.GetString("MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAY.
        /// </summary>
        internal static string MAY {
            get {
                return ResourceManager.GetString("MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a status or comment......
        /// </summary>
        internal static string MeasurementPlaceholder {
            get {
                return ResourceManager.GetString("MeasurementPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has been successfully sent..
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will not be functional until company has defined measurement period..
        /// </summary>
        internal static string MissingTemplate {
            get {
                return ResourceManager.GetString("MissingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR MOTIVATION.
        /// </summary>
        internal static string Motivation {
            get {
                return ResourceManager.GetString("Motivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTIVATION FACTOR.
        /// </summary>
        internal static string MotivationFactor {
            get {
                return ResourceManager.GetString("MotivationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation factors.
        /// </summary>
        internal static string MotivationFactorRank {
            get {
                return ResourceManager.GetString("MotivationFactorRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotivationPulse.
        /// </summary>
        internal static string MotivationPulse {
            get {
                return ResourceManager.GetString("MotivationPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: .
        /// </summary>
        internal static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My inbox.
        /// </summary>
        internal static string MyInbox {
            get {
                return ResourceManager.GetString("MyInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW GOAL.
        /// </summary>
        internal static string NewGoal {
            get {
                return ResourceManager.GetString("NewGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW TASK.
        /// </summary>
        internal static string NewMeasure {
            get {
                return ResourceManager.GetString("NewMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New target number is
        ///added to your goals..
        /// </summary>
        internal static string NewTargetNumber {
            get {
                return ResourceManager.GetString("NewTargetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next call.
        /// </summary>
        internal static string NextCall {
            get {
                return ResourceManager.GetString("NextCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT ONE-ON-ONE.
        /// </summary>
        internal static string NextCallHome {
            get {
                return ResourceManager.GetString("NextCallHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera.
        /// </summary>
        internal static string NoCamera {
            get {
                return ResourceManager.GetString("NoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don&apos;t have internet connection.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not that important.
        /// </summary>
        internal static string NotImportant {
            get {
                return ResourceManager.GetString("NotImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format!.
        /// </summary>
        internal static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not valid!.
        /// </summary>
        internal static string NotValidPassword {
            get {
                return ResourceManager.GetString("NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVEMBER.
        /// </summary>
        internal static string NOVEMBER {
            get {
                return ResourceManager.GetString("NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCTOBER.
        /// </summary>
        internal static string OCTOBER {
            get {
                return ResourceManager.GetString("OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string OperationConfirmed {
            get {
                return ResourceManager.GetString("OperationConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission not granted.
        /// </summary>
        internal static string PermissionNotGranted {
            get {
                return ResourceManager.GetString("PermissionNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a description of the target....
        /// </summary>
        internal static string PlaceholderNewTodo {
            get {
                return ResourceManager.GetString("PlaceholderNewTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference value is less than the current rating. Please, try again..
        /// </summary>
        internal static string preference_value_less_than_current_rating {
            get {
                return ResourceManager.GetString("preference_value_less_than_current_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference has been successfully updated..
        /// </summary>
        internal static string PreferenceUpdated {
            get {
                return ResourceManager.GetString("PreferenceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a pretty great extent.
        /// </summary>
        internal static string PrettyGreatExtent {
            get {
                return ResourceManager.GetString("PrettyGreatExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty important.
        /// </summary>
        internal static string PrettyImportant {
            get {
                return ResourceManager.GetString("PrettyImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIOUS.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review for previous period.
        /// </summary>
        internal static string PreviousReview {
            get {
                return ResourceManager.GetString("PreviousReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You prioritized this as:.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE PROFILE.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you feel about.
        /// </summary>
        internal static string QuestionEvaluate {
            get {
                return ResourceManager.GetString("QuestionEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you feel about communication and feedback from your lider right now?.
        /// </summary>
        internal static string QuestionEvaluateFactor {
            get {
                return ResourceManager.GetString("QuestionEvaluateFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire has been successfully answered and rating value updated..
        /// </summary>
        internal static string QuestionnaireUpdate {
            get {
                return ResourceManager.GetString("QuestionnaireUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating value has been successfully updated..
        /// </summary>
        internal static string RatingUpdate {
            get {
                return ResourceManager.GetString("RatingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieved.
        /// </summary>
        internal static string Realized {
            get {
                return ResourceManager.GetString("Realized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really important.
        /// </summary>
        internal static string ReallyImportant {
            get {
                return ResourceManager.GetString("ReallyImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received a photo.
        /// </summary>
        internal static string ReceivedPhoto {
            get {
                return ResourceManager.GetString("ReceivedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment and onboarding.
        /// </summary>
        internal static string RecruitmentAndOnboarding {
            get {
                return ResourceManager.GetString("RecruitmentAndOnboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you experience the recruitment and onboarding process as professional, welcoming and motivating for new employees?.
        /// </summary>
        internal static string RecruitmentAndOnboardingQuestion {
            get {
                return ResourceManager.GetString("RecruitmentAndOnboardingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, it is crucial for an organization to find the right people – people who fit into the culture, has the right values and attitudes, and can grow together with the organization. Further, the onboarding is about getting new employees included into the organization’s culture, both social and professional, and for the employees to become a productive part of the company. Often, the recruitment- and onboarding processes can have a major impact on the employees’ first impression of the organization and influ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecruitmentAndOnboardingText {
            get {
                return ResourceManager.GetString("RecruitmentAndOnboardingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been renewed!.
        /// </summary>
        internal static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign the review. Please, try again or contact the support..
        /// </summary>
        internal static string ReportSignFailed {
            get {
                return ResourceManager.GetString("ReportSignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible: .
        /// </summary>
        internal static string ResponsibleDetails {
            get {
                return ResourceManager.GetString("ResponsibleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSIBLE.
        /// </summary>
        internal static string ResponsiblePerson {
            get {
                return ResourceManager.GetString("ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your goals and achieved values.
        /// </summary>
        internal static string ReviewAchievement {
            get {
                return ResourceManager.GetString("ReviewAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review file.
        /// </summary>
        internal static string ReviewFileHeader {
            get {
                return ResourceManager.GetString("ReviewFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-on-ones.
        /// </summary>
        internal static string ReviewsHeader {
            get {
                return ResourceManager.GetString("ReviewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find any reviews for this user.
        /// </summary>
        internal static string ReviewsNotFound {
            get {
                return ResourceManager.GetString("ReviewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This gives you an overview of previously done one-on-one with your manager.
        /// </summary>
        internal static string ReviewsText {
            get {
                return ResourceManager.GetString("ReviewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed one-on-ones.
        /// </summary>
        internal static string ReviewsTitle {
            get {
                return ResourceManager.GetString("ReviewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree do today’s salary system motivate you?.
        /// </summary>
        internal static string SalaryQuestion {
            get {
                return ResourceManager.GetString("SalaryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think the current payment structure is motivating in your everyday work life?.
        /// </summary>
        internal static string SalaryText {
            get {
                return ResourceManager.GetString("SalaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled time: .
        /// </summary>
        internal static string ScheduledTime {
            get {
                return ResourceManager.GetString("ScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string SecondProgressBarDescription {
            get {
                return ResourceManager.GetString("SecondProgressBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section comment.
        /// </summary>
        internal static string SectionCommentTitle {
            get {
                return ResourceManager.GetString("SectionCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager hasn&apos;t wrote any comment for this section.
        /// </summary>
        internal static string SectionDefaultComment {
            get {
                return ResourceManager.GetString("SectionDefaultComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message to your closest manager.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior manager.
        /// </summary>
        internal static string SeniorManager {
            get {
                return ResourceManager.GetString("SeniorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        internal static string SenseOfAchievement {
            get {
                return ResourceManager.GetString("SenseOfAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you feel that your employer enables you to achieve your tasks in the best way?.
        /// </summary>
        internal static string SenseOfAchievementQuestion {
            get {
                return ResourceManager.GetString("SenseOfAchievementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what degree you feel that you achieve your tasks at work and master the work situation can often have a direct impact on your future motivation and wish to learn and take on more tasks. Your own efforts are crucial, obviously, but it is also important to feel that new tasks and challenges assigned to you are realistic, adjusted to your level and facilitates a gradual professional development..
        /// </summary>
        internal static string SenseOfAchievementText {
            get {
                return ResourceManager.GetString("SenseOfAchievementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sent a photo.
        /// </summary>
        internal static string SentPhoto {
            get {
                return ResourceManager.GetString("SentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTEMBER.
        /// </summary>
        internal static string SEPTEMBER {
            get {
                return ResourceManager.GetString("SEPTEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to set new goals?.
        /// </summary>
        internal static string SetNewGoals {
            get {
                return ResourceManager.GetString("SetNewGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a small extent.
        /// </summary>
        internal static string SmallExtent {
            get {
                return ResourceManager.GetString("SmallExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture and social environment.
        /// </summary>
        internal static string SocialEnvironment {
            get {
                return ResourceManager.GetString("SocialEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How satisfied are you with the organization’s social environment, cooperation and support from your colleagues?.
        /// </summary>
        internal static string SocialEnvironmentQuestion {
            get {
                return ResourceManager.GetString("SocialEnvironmentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think the organization has a good social environment, cooperation, and support between colleges?.
        /// </summary>
        internal static string SocialEnvironmentText {
            get {
                return ResourceManager.GetString("SocialEnvironmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To some extent.
        /// </summary>
        internal static string SomeExtent {
            get {
                return ResourceManager.GetString("SomeExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a status or comment.
        /// </summary>
        internal static string StatusComment {
            get {
                return ResourceManager.GetString("StatusComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        internal static string StatusDetails {
            get {
                return ResourceManager.GetString("StatusDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been successfully added.
        /// </summary>
        internal static string TaskAdd {
            get {
                return ResourceManager.GetString("TaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR TASKS.
        /// </summary>
        internal static string TasksTitle {
            get {
                return ResourceManager.GetString("TasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been succesfully updated.
        /// </summary>
        internal static string TaskUpdate {
            get {
                return ResourceManager.GetString("TaskUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        internal static string TermsAccept {
            get {
                return ResourceManager.GetString("TermsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string TermsCancel {
            get {
                return ResourceManager.GetString("TermsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept terms and conditions.
        /// </summary>
        internal static string TermsCheckbox {
            get {
                return ResourceManager.GetString("TermsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read terms and conditions before you start using it..
        /// </summary>
        internal static string TermsHeader {
            get {
                return ResourceManager.GetString("TermsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS AND CONDITIONS.
        /// </summary>
        internal static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback..
        /// </summary>
        internal static string ThankFeedback {
            get {
                return ResourceManager.GetString("ThankFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not respond quickly enough. Please, try again or contact our support..
        /// </summary>
        internal static string TimeoutMessage {
            get {
                return ResourceManager.GetString("TimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: .
        /// </summary>
        internal static string TitleMsg {
            get {
                return ResourceManager.GetString("TitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        internal static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you doing to reach your goals? See below for what tasks you are set to complete this period..
        /// </summary>
        internal static string ToDoSubtext {
            get {
                return ResourceManager.GetString("ToDoSubtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPIC.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We weren&apos;t able to recover your password. You may have entered the wrong username and we recommend that you try again or contact our support (/support)..
        /// </summary>
        internal static string UnableRecoverMessage {
            get {
                return ResourceManager.GetString("UnableRecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to answer questions from your employer!.
        /// </summary>
        internal static string UnansweredQuestions {
            get {
                return ResourceManager.GetString("UnansweredQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged out, please re-login. This happens if your security token is expired..
        /// </summary>
        internal static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATED.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR PREFERENCE IS UPDATED.
        /// </summary>
        internal static string UpdatedPreference {
            get {
                return ResourceManager.GetString("UpdatedPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update task.
        /// </summary>
        internal static string UpdateMeasure {
            get {
                return ResourceManager.GetString("UpdateMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE GOAL.
        /// </summary>
        internal static string UpdateMeasurement {
            get {
                return ResourceManager.GetString("UpdateMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to NEXT or click OK to exit..
        /// </summary>
        internal static string UpdatePreferenceMessage {
            get {
                return ResourceManager.GetString("UpdatePreferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR PREFERENCE HAS BEEN UPDATED.
        /// </summary>
        internal static string UpdatePreferenceTitle {
            get {
                return ResourceManager.GetString("UpdatePreferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update current rating.
        /// </summary>
        internal static string UpdateRating {
            get {
                return ResourceManager.GetString("UpdateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update achieved goal.
        /// </summary>
        internal static string UpdateRealizedGoal {
            get {
                return ResourceManager.GetString("UpdateRealizedGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR SITUATION IS UPDATED.
        /// </summary>
        internal static string UpdateSituation {
            get {
                return ResourceManager.GetString("UpdateSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status and achieved value.
        /// </summary>
        internal static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status and achieved goals.
        /// </summary>
        internal static string UpdateStatusAndGoals {
            get {
                return ResourceManager.GetString("UpdateStatusAndGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string UpdateUpp {
            get {
                return ResourceManager.GetString("UpdateUpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days since the last update.
        /// </summary>
        internal static string UpdatingText {
            get {
                return ResourceManager.GetString("UpdatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed by you.
        /// </summary>
        internal static string UserSignatureHeader {
            get {
                return ResourceManager.GetString("UserSignatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, make sure none of the fields is empty before submiting the form..
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a very great extent.
        /// </summary>
        internal static string VeryGreatExtent {
            get {
                return ResourceManager.GetString("VeryGreatExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of very little importance.
        /// </summary>
        internal static string VeryLittleImportance {
            get {
                return ResourceManager.GetString("VeryLittleImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a very small extent.
        /// </summary>
        internal static string VerySmallExtent {
            get {
                return ResourceManager.GetString("VerySmallExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTIVATION.
        /// </summary>
        internal static string ViewOverviewMotivation {
            get {
                return ResourceManager.GetString("ViewOverviewMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total can&apos;t exceed 60..
        /// </summary>
        internal static string ViewRankMax {
            get {
                return ResourceManager.GetString("ViewRankMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTIVATION.
        /// </summary>
        internal static string ViewRankMotivation {
            get {
                return ResourceManager.GetString("ViewRankMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} points left
        ///before you reach the limit..
        /// </summary>
        internal static string ViewRankNumbers {
            get {
                return ResourceManager.GetString("ViewRankNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0}
        /// points left before you reach the limit..
        /// </summary>
        internal static string ViewRankNumbers2 {
            get {
                return ResourceManager.GetString("ViewRankNumbers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What motivates you?.
        /// </summary>
        internal static string ViewRankQuestion {
            get {
                return ResourceManager.GetString("ViewRankQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences and motivational factors are shown on a scale from 1 to 10.
        /// </summary>
        internal static string ViewRankScale {
            get {
                return ResourceManager.GetString("ViewRankScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What goals are you working towards this period? 
        ///You can also add new goals.
        /// </summary>
        internal static string WhatGoal {
            get {
                return ResourceManager.GetString("WhatGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What motivates you at work?
        ///Register your preferences..
        /// </summary>
        internal static string WhatsImportant {
            get {
                return ResourceManager.GetString("WhatsImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WON CONTRACTS.
        /// </summary>
        internal static string WonContracts {
            get {
                return ResourceManager.GetString("WonContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message....
        /// </summary>
        internal static string WriteMessage {
            get {
                return ResourceManager.GetString("WriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        internal static string wrong_username_password {
            get {
                return ResourceManager.GetString("wrong_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR ACHIEVEMENT.
        /// </summary>
        internal static string YourAchievement {
            get {
                return ResourceManager.GetString("YourAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your development.
        /// </summary>
        internal static string YourDevelopment {
            get {
                return ResourceManager.GetString("YourDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string YourGoal {
            get {
                return ResourceManager.GetString("YourGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR GOALS.
        /// </summary>
        internal static string YourGoals {
            get {
                return ResourceManager.GetString("YourGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Leader.
        /// </summary>
        internal static string YourLeader {
            get {
                return ResourceManager.GetString("YourLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your motivation.
        /// </summary>
        internal static string YourMotivation {
            get {
                return ResourceManager.GetString("YourMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile.
        /// </summary>
        internal static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
