//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnboardingSoftware.App.LanguageSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class nb_no {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nb_no() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motivation.Core.LanguageSupport.nb-no", typeof(nb_no).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre og logg inn.
        /// </summary>
        internal static string AcceptAndLogin {
            get {
                return ResourceManager.GetString("AcceptAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGG TIL.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestasjonen ble lagt til..
        /// </summary>
        internal static string AddAchievement {
            get {
                return ResourceManager.GetString("AddAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGG TIL MÅL.
        /// </summary>
        internal static string AddGoal {
            get {
                return ResourceManager.GetString("AddGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til nye mål.
        /// </summary>
        internal static string AddNewGoal {
            get {
                return ResourceManager.GetString("AddNewGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til nytt tiltak.
        /// </summary>
        internal static string AddNewMeasurement {
            get {
                return ResourceManager.GetString("AddNewMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt tiltak er lagt til.
        /// </summary>
        internal static string AddNewMeasurementDialog {
            get {
                return ResourceManager.GetString("AddNewMeasurementDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGJEN.
        /// </summary>
        internal static string Again {
            get {
                return ResourceManager.GetString("Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil....
        /// </summary>
        internal static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En feil oppsto .
        /// </summary>
        internal static string AlertErrorMessage {
            get {
                return ResourceManager.GetString("AlertErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appcenter kunne ikke slette enheten din..
        /// </summary>
        internal static string AppcenterError {
            get {
                return ResourceManager.GetString("AppcenterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRIL.
        /// </summary>
        internal static string APRIL {
            get {
                return ResourceManager.GetString("APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUGUST.
        /// </summary>
        internal static string AUGUST {
            get {
                return ResourceManager.GetString("AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veldig dårlig.
        /// </summary>
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Får ikke kontaktet server, mulig oppgradering pågår..
        /// </summary>
        internal static string BadGatewayMessage {
            get {
                return ResourceManager.GetString("BadGatewayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De største gapene.
        /// </summary>
        internal static string BiggestGaps {
            get {
                return ResourceManager.GetString("BiggestGaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lederen har ikke skrevet noen kommentar for denne samtalen.
        /// </summary>
        internal static string BlankComment {
            get {
                return ResourceManager.GetString("BlankComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen kamera tilgjengelig.
        /// </summary>
        internal static string CameraAvailable {
            get {
                return ResourceManager.GetString("CameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg                                                                                                                                                                                           .
        /// </summary>
        internal static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå til neste eller OK for å avslutte..
        /// </summary>
        internal static string ClickOkNext {
            get {
                return ResourceManager.GetString("ClickOkNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjennomførte.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nærmeste leder.
        /// </summary>
        internal static string ClosestManager {
            get {
                return ResourceManager.GetString("ClosestManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommenter strom utvikling.
        /// </summary>
        internal static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GJENNOMFØRTE SALGSMØTER.
        /// </summary>
        internal static string CompletedSales {
            get {
                return ResourceManager.GetString("CompletedSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMTALER.
        /// </summary>
        internal static string Conversation {
            get {
                return ResourceManager.GetString("Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtaler.
        /// </summary>
        internal static string Conversations {
            get {
                return ResourceManager.GetString("Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helt avgjørende.
        /// </summary>
        internal static string Crucial {
            get {
                return ResourceManager.GetString("Crucial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato: .
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato ikke satt.
        /// </summary>
        internal static string DateNotSet {
            get {
                return ResourceManager.GetString("DateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udefinert.
        /// </summary>
        internal static string DateUndefined {
            get {
                return ResourceManager.GetString("DateUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIST.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frist.
        /// </summary>
        internal static string DeadlineDetails {
            get {
                return ResourceManager.GetString("DeadlineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESEMBER.
        /// </summary>
        internal static string DECEMBER {
            get {
                return ResourceManager.GetString("DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avdeling.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse: .
        /// </summary>
        internal static string DescriptionDetails {
            get {
                return ResourceManager.GetString("DescriptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BESKRIVELSE.
        /// </summary>
        internal static string DescriptionTodo {
            get {
                return ResourceManager.GetString("DescriptionTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videreutvikling.
        /// </summary>
        internal static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at selskapet legger til rette for en tilfredsstillende faglig utvikling?.
        /// </summary>
        internal static string DevelopmentQuestion {
            get {
                return ResourceManager.GetString("DevelopmentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med videreutvikling menes mulighetene du har ved din arbeidsplass til å lære noe nytt og utvikle deg faglig ved å sette deg inn i nye problemstillinger og løse nye oppgaver. Det å ha mulighet til å lære seg noe nytt og bli utfordret på nye områder utvider den enkeltes kompetanseområder. Mange motiveres av å stadig utvikle sin kompetanse..
        /// </summary>
        internal static string DevelopmentText {
            get {
                return ResourceManager.GetString("DevelopmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last ned PDF-fil.
        /// </summary>
        internal static string DownloadPdfFile {
            get {
                return ResourceManager.GetString("DownloadPdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dra eller bruk knappene for å øke eller minske fort.
        /// </summary>
        internal static string DragUseButtons1 {
            get {
                return ResourceManager.GetString("DragUseButtons1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her bruker du en skala fra 1 til 10 til å rangere hvilke faktorer som motiverer deg på jobb, hvor 10 tilsvarer noe som er veldig viktig for deg.
        /// </summary>
        internal static string DragUseButtons2 {
            get {
                return ResourceManager.GetString("DragUseButtons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REDIGER TILTAK.
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du vil motta en e-post så kan du tilbakestille passordet ditt..
        /// </summary>
        internal static string EnableRecoverMessage {
            get {
                return ResourceManager.GetString("EnableRecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veldig god.
        /// </summary>
        internal static string Excelent {
            get {
                return ResourceManager.GetString("Excelent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvordan opplever du situasjonen på nåværende tidspunkt?.
        /// </summary>
        internal static string Expectations {
            get {
                return ResourceManager.GetString("Expectations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andre goder.
        /// </summary>
        internal static string ExtraBenefits {
            get {
                return ResourceManager.GetString("ExtraBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at de godene selskapet tilbyr de ansatte i dag motiverer deg i arbeidshverdagen?.
        /// </summary>
        internal static string ExtraBenefitsQuestion {
            get {
                return ResourceManager.GetString("ExtraBenefitsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er viktig å bli belønnet for arbeidet man gjør og verdiene man skaper for selskapet man jobber for, men ikke nødvendigvis alltid gjennom lønn eller bonus gitt i kroner. Mange setter pris på andre såkalte frynsegoder, som også kan benyttes utenfor arbeidstiden og eventuelt etter endt karriere..
        /// </summary>
        internal static string ExtraBenefitsText {
            get {
                return ResourceManager.GetString("ExtraBenefitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilrettelegging og fleksibilitet.
        /// </summary>
        internal static string FacilitationAndFlexibility {
            get {
                return ResourceManager.GetString("FacilitationAndFlexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at det blir lagt til rette og utvist fleksibilitet for dine behov på arbeidsplassen?.
        /// </summary>
        internal static string FacilitationAndFlexibilityQuestion {
            get {
                return ResourceManager.GetString("FacilitationAndFlexibilityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleksibilitet på arbeidsplassen er viktig for mange - kanskje spesielt om man har barn eller andre forpliktelser. En fleksibel arbeidsplass kan for eksempel legge til rette for fleksibel arbeidstid og muligheter for å opparbeide avspasering, muligheter for å arbeide hjemmefra eller fra andre lokasjoner og fleksibilitet rundt når man kan ta seg ferie. Utover dette handler det også om at arbeidsgiver generelt legger til rette for at du som arbeidstaker kan gjøre jobben din på best mulig måte..
        /// </summary>
        internal static string FacilitationAndFlexibilityText {
            get {
                return ResourceManager.GetString("FacilitationAndFlexibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktorer.
        /// </summary>
        internal static string Factors {
            get {
                return ResourceManager.GetString("Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEBRUAR.
        /// </summary>
        internal static string FEBRUARY {
            get {
                return ResourceManager.GetString("FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lederen din har signert samtalen, vennligst gjør det samme!.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikasjon og tilbakemeldinger.
        /// </summary>
        internal static string FeedbackAndCommunication {
            get {
                return ResourceManager.GetString("FeedbackAndCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at du får tilstrekkelige og relevante tilbakemeldinger og oppfølging vedrørende ditt arbeid og prestasjon?.
        /// </summary>
        internal static string FeedbackAndCommunicationQuestion {
            get {
                return ResourceManager.GetString("FeedbackAndCommunicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For den enkelte er det vesentlig å få tilbakemeldinger på arbeidssituasjon og prestasjoner. Hvordan gjør jeg det egentlig i jobben min? God veiledning er avhengig av god kommunikasjonsflyt, åpenhet og rom for å stille spørsmål. Oppfølging fra ledere, med klare målsettinger og konstruktive, løpende tilbakemeldinger er viktig..
        /// </summary>
        internal static string FeedbackAndCommunicationText {
            get {
                return ResourceManager.GetString("FeedbackAndCommunicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filen er lastet ned.
        /// </summary>
        internal static string FileDownloaded {
            get {
                return ResourceManager.GetString("FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ved å klikke på fil vil den bli åpnet i pdf visningen.
        /// </summary>
        internal static string FileViewerInfo {
            get {
                return ResourceManager.GetString("FileViewerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nåsituasjon.
        /// </summary>
        internal static string FirstProgressBarDescription {
            get {
                return ResourceManager.GetString("FirstProgressBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glemt brukernavn eller passord?.
        /// </summary>
        internal static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullt navn.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hent glemt passord.
        /// </summary>
        internal static string GetForgottenPassword {
            get {
                return ResourceManager.GetString("GetForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mål.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mål:.
        /// </summary>
        internal static string GoalDetails {
            get {
                return ResourceManager.GetString("GoalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Målet er ikke satt.
        /// </summary>
        internal static string GoalNotSet {
            get {
                return ResourceManager.GetString("GoalNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÅL.
        /// </summary>
        internal static string GoalOverview {
            get {
                return ResourceManager.GetString("GoalOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine måltall er oppdatert..
        /// </summary>
        internal static string GoalUpdated {
            get {
                return ResourceManager.GetString("GoalUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helt OK.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God morgen!.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GODT JOBBA.
        /// </summary>
        internal static string GoodWork {
            get {
                return ResourceManager.GetString("GoodWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I stor grad.
        /// </summary>
        internal static string GreatExtent {
            get {
                return ResourceManager.GetString("GreatExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjem.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortell virksomheten din hva som motiverer deg på jobb!.
        /// </summary>
        internal static string HomeViewMessage {
            get {
                return ResourceManager.GetString("HomeViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felles identitet og tydelig visjon.
        /// </summary>
        internal static string IdentityAndVision {
            get {
                return ResourceManager.GetString("IdentityAndVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at virksomheten har en godt forankret identitet, felles mål og en tydelig visjon?.
        /// </summary>
        internal static string IdentityAndVisionQuestion {
            get {
                return ResourceManager.GetString("IdentityAndVisionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noen virksomheter lykkes med å etablere en felles identitet knyttet til virksomheten som gjør at de ansatte er stolte av å representere og arbeide for selskapet og opplever at de bidrar til et fellesskap og noe mer enn bare sine egne individuelle mål. Det er gjerne over tid utviklet et sett av verdier og bånd mellom virksomheten og de ansatte som de ansatte verdsetter og identifiserer seg med. Felles kjerneverdier og en klar visjon i virksomheten kan bidra til at arbeidet føles meningsfullt..
        /// </summary>
        internal static string IdentityAndVisionText {
            get {
                return ResourceManager.GetString("IdentityAndVisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middels viktig.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her ser du hvordan du har rangert alle motivasjonsfaktorene.
        /// </summary>
        internal static string ImprovementTitle {
            get {
                return ResourceManager.GetString("ImprovementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldinger.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruk knappene for å øke eller minske verdien.
        /// </summary>
        internal static string IncreaseDecreaseButton {
            get {
                return ResourceManager.GetString("IncreaseDecreaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasjon.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne rapporten kan ikke lastes ned før lederen har signert den..
        /// </summary>
        internal static string InvalidDownload {
            get {
                return ResourceManager.GetString("InvalidDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filen kan ikke lastes inn eller lastet feil. Prøv igjen eller kontakt support..
        /// </summary>
        internal static string InvalidFileLoad {
            get {
                return ResourceManager.GetString("InvalidFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medbestemmelse.
        /// </summary>
        internal static string Involvement {
            get {
                return ResourceManager.GetString("Involvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at du har innflytelse på din egen arbeidssituasjon i dag?.
        /// </summary>
        internal static string InvolvementQuestion {
            get {
                return ResourceManager.GetString("InvolvementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mange trives med å ha en klar innflytelse på egen arbeidssituasjon og jobbe et sted med rom for å komme med egne meninger. Dette kan være innenfor ulike områder som f. eks. hvilke oppgaver som bør utføres og hvordan de bør utføres. Det å selv ha en klar innflytelse på egen arbeidshverdag og «ha et ord med i laget» kan for mange virke svært motiverende..
        /// </summary>
        internal static string InvolvementText {
            get {
                return ResourceManager.GetString("InvolvementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JANUAR.
        /// </summary>
        internal static string JANUARY {
            get {
                return ResourceManager.GetString("JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JULI.
        /// </summary>
        internal static string JULY {
            get {
                return ResourceManager.GetString("JULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNI.
        /// </summary>
        internal static string JUNE {
            get {
                return ResourceManager.GetString("JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Språkfeil.
        /// </summary>
        internal static string LanguageError {
            get {
                return ResourceManager.GetString("LanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Språk ikke satt i selskapets innstillinger.
        /// </summary>
        internal static string LanguageErrorMessage {
            get {
                return ResourceManager.GetString("LanguageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vennligst velg et av språkene for applikasjonen.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg språk.
        /// </summary>
        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lederen din.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne samtalen kan ikke signeres før lederen har signert den første..
        /// </summary>
        internal static string LeaderNotSigned {
            get {
                return ResourceManager.GetString("LeaderNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINDRE.
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er logget inn.
        ///Takk for at du har valgt å bruke eMotivation tjenesten!.
        /// </summary>
        internal static string LoggedInMessage {
            get {
                return ResourceManager.GetString("LoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logget inn.
        /// </summary>
        internal static string LoggedInTitle {
            get {
                return ResourceManager.GetString("LoggedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil brukernavn eller passord.
        /// </summary>
        internal static string loggin_recover_sent {
            get {
                return ResourceManager.GetString("loggin_recover_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGG INN.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din autentifisering er utgått. Vennligst logg inn pånytt..
        /// </summary>
        internal static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg ut.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er i ferd med å logge ut, er du sikker på det?.
        /// </summary>
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger ut.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glemt passord.
        /// </summary>
        internal static string LostPasswordTitle {
            get {
                return ResourceManager.GetString("LostPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leder: .
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signert av manager.
        /// </summary>
        internal static string ManagerSignatureHeader {
            get {
                return ResourceManager.GetString("ManagerSignatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS.
        /// </summary>
        internal static string MARCH {
            get {
                return ResourceManager.GetString("MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAI.
        /// </summary>
        internal static string MAY {
            get {
                return ResourceManager.GetString("MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine Måltall.
        /// </summary>
        internal static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en status eller kommentar…...
        /// </summary>
        internal static string MeasurementPlaceholder {
            get {
                return ResourceManager.GetString("MeasurementPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldingen er sendt..
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søknad vil ikke være funksjonell før selskapet har definert måleperiode..
        /// </summary>
        internal static string MissingTemplate {
            get {
                return ResourceManager.GetString("MissingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MER.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN MOTIVASJON.
        /// </summary>
        internal static string Motivation {
            get {
                return ResourceManager.GetString("Motivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTIVASJONSFAKTOR.
        /// </summary>
        internal static string MotivationFactor {
            get {
                return ResourceManager.GetString("MotivationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivasjonsfaktor .
        /// </summary>
        internal static string MotivationFactorRank {
            get {
                return ResourceManager.GetString("MotivationFactorRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotivasjonsPulsen.
        /// </summary>
        internal static string MotivationPulse {
            get {
                return ResourceManager.GetString("MotivationPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding: .
        /// </summary>
        internal static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine meldinger.
        /// </summary>
        internal static string MyInbox {
            get {
                return ResourceManager.GetString("MyInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYTT MÅL.
        /// </summary>
        internal static string NewGoal {
            get {
                return ResourceManager.GetString("NewGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYTT TILTAK.
        /// </summary>
        internal static string NewMeasure {
            get {
                return ResourceManager.GetString("NewMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt måltall er lagt til dine mål..
        /// </summary>
        internal static string NewTargetNumber {
            get {
                return ResourceManager.GetString("NewTargetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NESTE.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neste samtale.
        /// </summary>
        internal static string NextCall {
            get {
                return ResourceManager.GetString("NextCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NESTE SAMTALE.
        /// </summary>
        internal static string NextCallHome {
            get {
                return ResourceManager.GetString("NextCallHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen kamera.
        /// </summary>
        internal static string NoCamera {
            get {
                return ResourceManager.GetString("NoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser ut som du ikke har internettforbindelse.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite viktig.
        /// </summary>
        internal static string NotImportant {
            get {
                return ResourceManager.GetString("NotImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost er ikke gyldig!.
        /// </summary>
        internal static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passord er ikke gyldig!.
        /// </summary>
        internal static string NotValidPassword {
            get {
                return ResourceManager.GetString("NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVEMBER.
        /// </summary>
        internal static string NOVEMBER {
            get {
                return ResourceManager.GetString("NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKTOBER.
        /// </summary>
        internal static string OCTOBER {
            get {
                return ResourceManager.GetString("OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apen.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekreftelse.
        /// </summary>
        internal static string OperationConfirmed {
            get {
                return ResourceManager.GetString("OperationConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasjonen feilet.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annet.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passord.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillatelse ikke gitt.
        /// </summary>
        internal static string PermissionNotGranted {
            get {
                return ResourceManager.GetString("PermissionNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en beskrivelse av målet....
        /// </summary>
        internal static string PlaceholderNewTodo {
            get {
                return ResourceManager.GetString("PlaceholderNewTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stilling.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferanseverdien er mindre enn nåværende vurdering.Vær så snill, prøv på nytt..
        /// </summary>
        internal static string preference_value_less_than_current_rating {
            get {
                return ResourceManager.GetString("preference_value_less_than_current_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferanser.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferansen er oppdatert..
        /// </summary>
        internal static string PreferenceUpdated {
            get {
                return ResourceManager.GetString("PreferenceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I ganske stor grad.
        /// </summary>
        internal static string PrettyGreatExtent {
            get {
                return ResourceManager.GetString("PrettyGreatExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganske viktig.
        /// </summary>
        internal static string PrettyImportant {
            get {
                return ResourceManager.GetString("PrettyImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORRIGE.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldelse av siste periode.
        /// </summary>
        internal static string PreviousReview {
            get {
                return ResourceManager.GetString("PreviousReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du prioriterte dette som:.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPPRETT PROFIL.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvordan opplever du at.
        /// </summary>
        internal static string QuestionEvaluate {
            get {
                return ResourceManager.GetString("QuestionEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvordan opplever du at kommunikasjon og tilbakemeldinger fra lederen din er på nåværende tidspunkt?.
        /// </summary>
        internal static string QuestionEvaluateFactor {
            get {
                return ResourceManager.GetString("QuestionEvaluateFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spørsmålene ble besvart og rangering er oppdatert..
        /// </summary>
        internal static string QuestionnaireUpdate {
            get {
                return ResourceManager.GetString("QuestionnaireUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangerings verdi ble oppdatert..
        /// </summary>
        internal static string RatingUpdate {
            get {
                return ResourceManager.GetString("RatingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realisert.
        /// </summary>
        internal static string Realized {
            get {
                return ResourceManager.GetString("Realized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veldig viktig.
        /// </summary>
        internal static string ReallyImportant {
            get {
                return ResourceManager.GetString("ReallyImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du mottok et bilde.
        /// </summary>
        internal static string ReceivedPhoto {
            get {
                return ResourceManager.GetString("ReceivedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekruttering og onboarding.
        /// </summary>
        internal static string RecruitmentAndOnboarding {
            get {
                return ResourceManager.GetString("RecruitmentAndOnboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du dagens rekruttering- og onboardingsprosesser som gode, imøtekommende og motiverende for nye ansatte?.
        /// </summary>
        internal static string RecruitmentAndOnboardingQuestion {
            get {
                return ResourceManager.GetString("RecruitmentAndOnboardingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er helt avgjørende for en bedrift å finne de riktige menneskene - som passer inn i kulturen, har de rette verdiene og holdningene og kan vokse sammen med organisasjonen. Deretter handler onboardingen om å raskest mulig komme inn i bedriftens kultur, både sosialt og faglig, og bli en produktiv del av bedriften. Ofte har både rekrutterings- og onboardingsprosessen mye å si for hva slags inntrykk en medarbeider får av virksomheten og hvilken motivasjon man har for å komme inn og gjøre sitt beste. Førsteinn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecruitmentAndOnboardingText {
            get {
                return ResourceManager.GetString("RecruitmentAndOnboardingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økten din er fornyet..
        /// </summary>
        internal static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke signere samtalen. Prøv igjen eller kontakt supporten..
        /// </summary>
        internal static string ReportSignFailed {
            get {
                return ResourceManager.GetString("ReportSignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansvarlig.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansvarlig: .
        /// </summary>
        internal static string ResponsibleDetails {
            get {
                return ResourceManager.GetString("ResponsibleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSVARLIG.
        /// </summary>
        internal static string ResponsiblePerson {
            get {
                return ResourceManager.GetString("ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjennomgang av mål du har satt deg.
        /// </summary>
        internal static string ReviewAchievement {
            get {
                return ResourceManager.GetString("ReviewAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fil.
        /// </summary>
        internal static string ReviewFileHeader {
            get {
                return ResourceManager.GetString("ReviewFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjennomførte samtaler.
        /// </summary>
        internal static string ReviewsHeader {
            get {
                return ResourceManager.GetString("ReviewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi fant ingen anmeldelser for denne brukeren.
        /// </summary>
        internal static string ReviewsNotFound {
            get {
                return ResourceManager.GetString("ReviewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her ser du en oversikt over tidligere gjennomførte samtaler med din leder.
        /// </summary>
        internal static string ReviewsText {
            get {
                return ResourceManager.GetString("ReviewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjennomførte samtaler.
        /// </summary>
        internal static string ReviewsTitle {
            get {
                return ResourceManager.GetString("ReviewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lønn.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hvilken grad motiverer dagens lønnssystem deg i arbeidshverdagen?.
        /// </summary>
        internal static string SalaryQuestion {
            get {
                return ResourceManager.GetString("SalaryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at dagens lønnssystem motiverer deg i arbeidshverdagen?.
        /// </summary>
        internal static string SalaryText {
            get {
                return ResourceManager.GetString("SalaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlagt tidspunkt: .
        /// </summary>
        internal static string ScheduledTime {
            get {
                return ResourceManager.GetString("ScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din preferanse.
        /// </summary>
        internal static string SecondProgressBarDescription {
            get {
                return ResourceManager.GetString("SecondProgressBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seksjonskommentar.
        /// </summary>
        internal static string SectionCommentTitle {
            get {
                return ResourceManager.GetString("SectionCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager har ikke skrevet noen kommentar for denne delen.
        /// </summary>
        internal static string SectionDefaultComment {
            get {
                return ResourceManager.GetString("SectionDefaultComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send en melding til din nærmeste leder.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overordnet leder.
        /// </summary>
        internal static string SeniorManager {
            get {
                return ResourceManager.GetString("SeniorManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mestring.
        /// </summary>
        internal static string SenseOfAchievement {
            get {
                return ResourceManager.GetString("SenseOfAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at forholdene er lagt til rette for at du skal lykkes med dine arbeidsoppgaver?.
        /// </summary>
        internal static string SenseOfAchievementQuestion {
            get {
                return ResourceManager.GetString("SenseOfAchievementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvor godt man føler at man mestrer arbeidssituasjonen og - oppgavene sine kan ofte ha direkte innvirkning på videre motivasjon og ønsket om lære mer og ta på seg andre oppgaver. I tillegg til egen innsats er det også viktig at man opplever at nye oppgaver og utfordringer er realistiske, tilpasset eget arbeidsnivå og legger opp til gradvis kompetanseheving..
        /// </summary>
        internal static string SenseOfAchievementText {
            get {
                return ResourceManager.GetString("SenseOfAchievementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du sendte et bilde.
        /// </summary>
        internal static string SentPhoto {
            get {
                return ResourceManager.GetString("SentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTEMBER.
        /// </summary>
        internal static string SEPTEMBER {
            get {
                return ResourceManager.GetString("SEPTEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du lyst til å sette deg nye mål?.
        /// </summary>
        internal static string SetNewGoals {
            get {
                return ResourceManager.GetString("SetNewGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I liten grad.
        /// </summary>
        internal static string SmallExtent {
            get {
                return ResourceManager.GetString("SmallExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kultur og sosialt miljø.
        /// </summary>
        internal static string SocialEnvironment {
            get {
                return ResourceManager.GetString("SocialEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvor fornøyd er du med det sosiale miljøet, samarbeidet med og støtten fra kollegaene dine?.
        /// </summary>
        internal static string SocialEnvironmentQuestion {
            get {
                return ResourceManager.GetString("SocialEnvironmentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opplever du at det er et godt sosialt miljø, samarbeid og støtte mellom kollegaer ved arbeidsplassen?.
        /// </summary>
        internal static string SocialEnvironmentText {
            get {
                return ResourceManager.GetString("SocialEnvironmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I noen grad.
        /// </summary>
        internal static string SomeExtent {
            get {
                return ResourceManager.GetString("SomeExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorter på.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjem.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en status eller kommentar.
        /// </summary>
        internal static string StatusComment {
            get {
                return ResourceManager.GetString("StatusComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        internal static string StatusDetails {
            get {
                return ResourceManager.GetString("StatusDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger tiltak.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emne.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppgaven ble lagt til.
        /// </summary>
        internal static string TaskAdd {
            get {
                return ResourceManager.GetString("TaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiltak.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DINE TILTAK.
        /// </summary>
        internal static string TasksTitle {
            get {
                return ResourceManager.GetString("TasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiltaket er oppdatert.
        /// </summary>
        internal static string TaskUpdate {
            get {
                return ResourceManager.GetString("TaskUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDERE.
        /// </summary>
        internal static string TermsAccept {
            get {
                return ResourceManager.GetString("TermsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVBRYT.
        /// </summary>
        internal static string TermsCancel {
            get {
                return ResourceManager.GetString("TermsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg aksepterer villkårene for bruk av denne løsningen..
        /// </summary>
        internal static string TermsCheckbox {
            get {
                return ResourceManager.GetString("TermsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vennligst les gjennom villkårene for bruk av informasjon i løsningen før du starter å benytte denne..
        /// </summary>
        internal static string TermsHeader {
            get {
                return ResourceManager.GetString("TermsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VILLKÅR FOR BRUK AV LØSNINGEN.
        /// </summary>
        internal static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takk for din tilbakemelding..
        /// </summary>
        internal static string ThankFeedback {
            get {
                return ResourceManager.GetString("ThankFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveren svarte ikke raskt nok. Vennligst prøv igjen eller kontakt vår support..
        /// </summary>
        internal static string TimeoutMessage {
            get {
                return ResourceManager.GetString("TimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel: .
        /// </summary>
        internal static string TitleMsg {
            get {
                return ResourceManager.GetString("TitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine tiltak.
        /// </summary>
        internal static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva skal du gjøre for å nå målene dine? 
        ///Her kan du se hvilke tiltak du skal gjennomføre denne perioden..
        /// </summary>
        internal static string ToDoSubtext {
            get {
                return ResourceManager.GetString("ToDoSubtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMNE.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi kunne ikke å tilbakestille passordet din. Du kan ha skrevet inn feil brukernavn og anbefaler vi at du prøver igjen, eller kontakter vår kundestøtte (/support)..
        /// </summary>
        internal static string UnableRecoverMessage {
            get {
                return ResourceManager.GetString("UnableRecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husk å svare på spørsmålene fra arbeidsgiveren din!.
        /// </summary>
        internal static string UnansweredQuestions {
            get {
                return ResourceManager.GetString("UnansweredQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du ble logget ut, dette skjer ofte etter inaktivitet. Vennligst logg inn på nytt..
        /// </summary>
        internal static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPPDATERT.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN PREFERENSE ER OPPDATERT.
        /// </summary>
        internal static string UpdatedPreference {
            get {
                return ResourceManager.GetString("UpdatedPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPPDATER MÅLTALL.
        /// </summary>
        internal static string UpdateMeasurement {
            get {
                return ResourceManager.GetString("UpdateMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå til neste eller OK for å avslutte..
        /// </summary>
        internal static string UpdatePreferenceMessage {
            get {
                return ResourceManager.GetString("UpdatePreferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN PREFERANSE ER OPPDATERT.
        /// </summary>
        internal static string UpdatePreferenceTitle {
            get {
                return ResourceManager.GetString("UpdatePreferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater nåsituasjon.
        /// </summary>
        internal static string UpdateRating {
            get {
                return ResourceManager.GetString("UpdateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater realiserte mål.
        /// </summary>
        internal static string UpdateRealizedGoal {
            get {
                return ResourceManager.GetString("UpdateRealizedGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN NÅSITUASJON ER OPPDATERT.
        /// </summary>
        internal static string UpdateSituation {
            get {
                return ResourceManager.GetString("UpdateSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater realiserte mål.
        /// </summary>
        internal static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater status og realiserte mål.
        /// </summary>
        internal static string UpdateStatusAndGoals {
            get {
                return ResourceManager.GetString("UpdateStatusAndGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPPDATER.
        /// </summary>
        internal static string UpdateUpp {
            get {
                return ResourceManager.GetString("UpdateUpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dager side siden siste oppdateing.
        /// </summary>
        internal static string UpdatingText {
            get {
                return ResourceManager.GetString("UpdatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil brukernavn eller passord.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukernavn.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signert av deg.
        /// </summary>
        internal static string UserSignatureHeader {
            get {
                return ResourceManager.GetString("UserSignatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vær sikker på at ingen av feltene er tomme før du sender inn skjemaet..
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I svært stor grad.
        /// </summary>
        internal static string VeryGreatExtent {
            get {
                return ResourceManager.GetString("VeryGreatExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veldig lite viktig.
        /// </summary>
        internal static string VeryLittleImportance {
            get {
                return ResourceManager.GetString("VeryLittleImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I svært liten grad.
        /// </summary>
        internal static string VerySmallExtent {
            get {
                return ResourceManager.GetString("VerySmallExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTIVASJON.
        /// </summary>
        internal static string ViewOverviewMotivation {
            get {
                return ResourceManager.GetString("ViewOverviewMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalsummen kan ikke overstige 60..
        /// </summary>
        internal static string ViewRankMax {
            get {
                return ResourceManager.GetString("ViewRankMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN MOTIVASJON.
        /// </summary>
        internal static string ViewRankMotivation {
            get {
                return ResourceManager.GetString("ViewRankMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har {0} poeng igjen
        ///før du når grensen..
        /// </summary>
        internal static string ViewRankNumbers {
            get {
                return ResourceManager.GetString("ViewRankNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har {0}
        /// poeng igjen før du når grensen..
        /// </summary>
        internal static string ViewRankNumbers2 {
            get {
                return ResourceManager.GetString("ViewRankNumbers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva motiverer deg?.
        /// </summary>
        internal static string ViewRankQuestion {
            get {
                return ResourceManager.GetString("ViewRankQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine preferanser og motivasjonsfaktorer prioritert på en en skala fra 1-10.
        /// </summary>
        internal static string ViewRankScale {
            get {
                return ResourceManager.GetString("ViewRankScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppmerksomhet.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvile mål skal du jobbe mot denne perioden?
        ///Her kan du også legge til nye mål.
        /// </summary>
        internal static string WhatGoal {
            get {
                return ResourceManager.GetString("WhatGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva motiverer deg på jobb? 
        ///Registrer dine preferanser..
        /// </summary>
        internal static string WhatsImportant {
            get {
                return ResourceManager.GetString("WhatsImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUNNET KONTRAKTER.
        /// </summary>
        internal static string WonContracts {
            get {
                return ResourceManager.GetString("WonContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv en beskjed....
        /// </summary>
        internal static string WriteMessage {
            get {
                return ResourceManager.GetString("WriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil brukernavn eller passord.
        /// </summary>
        internal static string wrong_username_password {
            get {
                return ResourceManager.GetString("wrong_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I går.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIN PRESTASJON.
        /// </summary>
        internal static string YourAchievement {
            get {
                return ResourceManager.GetString("YourAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din utvikling.
        /// </summary>
        internal static string YourDevelopment {
            get {
                return ResourceManager.GetString("YourDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine mål.
        /// </summary>
        internal static string YourGoal {
            get {
                return ResourceManager.GetString("YourGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DINE MÅL.
        /// </summary>
        internal static string YourGoals {
            get {
                return ResourceManager.GetString("YourGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din leder.
        /// </summary>
        internal static string YourLeader {
            get {
                return ResourceManager.GetString("YourLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din motivasjon.
        /// </summary>
        internal static string YourMotivation {
            get {
                return ResourceManager.GetString("YourMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din profil.
        /// </summary>
        internal static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
